name: Release Workflow

on:
  release:
    types: [released]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build and deployment steps here
      # For example, you can use npm, yarn, or any other build tool

      - name: Build
        run: yarn && yarn build

      # Add your deployment steps here
      # For example, deploying to a web server, cloud service, etc.
